version: "3"
volumes:
  database:
  search_conf:
services:
  pgsql:
    container_name: pgsql
    image: postgres
    environment:
      POSTGRES_USER: bountysource
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  sphinx:
    container_name: sphinx
    image: leodido/sphinxsearch:2.2.9
    hostname: sphinx
    command: searchd.sh
    links:
      - pgsql
    volumes:
      - .:/app
      - search_conf:/usr/local/etc/
    ports:
      - "9306:9306"
      - "9312:9312"
  bountysource:
    container_name: bountysource
    image: bountysource
    env_file: .env
    links:
      - pgsql
      - sphinx
      - elasticsearch
    build: .
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    command: rails s Puma
    volumes:
      - .:/app
  delayedjob:
    container_name: delayedjob
    image: bountysource
    env_file: .env
    links:
      - bountysource
      - pgsql
      - sphinx
    build: .
    command: bundle exec rake jobs:work
    volumes:
      - .:/app
  elasticsearch:
    image: elasticsearch:6.8.8
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
